### ISSUE TITLE
Handling Cantrips Suggestion

### ISSUE THREAD

**Issue by fasrial** [TNychka/Pathfinder2eConversion#56]
https://github.com/TNychka/Pathfinder2eConversion/blob/d3e7002686af3c489a53ed21dfc556749ca4996e/Subsections/dragonmarks.txt#L727

I'd suggest swapping out Daze and Tanglefoot for Protect Companion and Tame, which fits the Dragonmark much better - they aren't known for their plant/alchemical affinities or being able to stun any target (although a Daze that worked only on animals could work).

**Comment by TNychka** [comment]
Modification made in dev stream 44cc2a245bafb2033e3e3176242779caa9816d6d for 1.1

Along with your other comments, this qualifies you as a contributor if you are so interested. Let me know if/what handle you want to be referred to as in the contributors doc!

**Comment by fasrial** [comment]
Very happy to do some more thorough looking in balance passes, this is such an awesome process! I’d be honored to be naked as a contributor - if people use their real names I’m happy to provide it, or if people use their handles Fasrial works too.
