### ISSUE TITLE
Camoflauge Stealth Bonus High and Typo

### ISSUE THREAD

**Issue by fasrial** [TNychka/Pathfinder2eConversion#57]
https://github.com/TNychka/Pathfinder2eConversion/blob/d3e7002686af3c489a53ed21dfc556749ca4996e/Subsections/eberron-changelings.txt#L110

Camoflauge I think should be spelled Camouflage, and a +4 circumstance bonus seems pretty high. I'd recommend a +1 bonus, and take out the need for cover/difficult terrain, but limit it to Hide checks (as moving camouflage would be a lot trickier).

**Comment by fasrial** [comment]
I neglected to realize that greater cover gives you a +4. Maybe granting a +1 circumstance bonus, as well as increasing the circumstance bonus by cover or greater cover by 1, might be appropriate?

**Comment by TNychka** [comment]
clsoing: cd42a66c0f339b4991e7c43b6cad24e0f9fae3b2
