### ISSUE TITLE
Kalaraq Leader Power Level

### ISSUE THREAD

**Issue by fasrial** [TNychka/Pathfinder2eConversion#58]
https://github.com/TNychka/Pathfinder2eConversion/blob/d3e7002686af3c489a53ed21dfc556749ca4996e/Subsections/kalashtar.txt#L292

The semi-constant +1 to saves and AC to an ally as a 5th level ancestry feat seems like it might be too much. Something that requires the leader to use their reaction to provide the benefit seems much more fair, but still powerful.

As a suggestion, basing it on the level 6 Guardian's Deflection fighter feat but making it only a +1 to account for it not requiring you to be in melee reach and because it's only an ancestry feat and not a class feat:

```
item(
# Kalaraq Leader :r:
## Feat 5
-
; Kalaraq Kalashtar heritage
**Trigger** An ally currently targeted by your Link Minds cantrip is hit by an attack, you can see the attacker, and the ally gaining a +1 circumstance bonus to AC would turn the critical hit into a hit or the hit into a miss.
-
The Kalaraq are the natural leaders of the Quori and can guide their followers to stand resolute. You grant your ally a +1 circumstance bonus to their Armor Class against the triggering attack. This turns the triggering critical hit into a hit, or the triggering hit into a miss.
)
```

**Comment by TNychka** [comment]
Adjusted to reaction requirement, and clarified usage in 4fbc11dafdbe3e47898050ebc4b6ff1410a347e8
