### ISSUE TITLE
Greatbows mentioned, only Gnoll Bows exist.

### ISSUE THREAD

**Issue by PaperMonkeyLord** [TNychka/Pathfinder2eConversion#74]
Greatbows are mentioned but never statted. A gnoll bow exists, but the gnoll weapon familiarity feats give flat out greatbow proficiency. Which is an advanced weapon if we're referring to gnoll bow instead. Some mixup here.

**Comment by TNychka** [comment]
Modified all references to Greatbows to Gnollbows instead. Given that the weapons are similar to greatbows, but specifically a gnoll ancestry weapon, the gnollbow is a more accurate name.
Closed in cf9dd2d92b936cadeb6a5dda9fa15999eb89af48
