### ISSUE TITLE
Clarification on Changeling Shift Shape ability

### ISSUE THREAD

**Issue by Foradain** [TNychka/Pathfinder2eConversion#80]
"You can Dismiss this spell.

Special You stay in the new form until you use shift shape to revert to your true form or until you die."

Does Dismissing the spell count as using the spell?  If so, does that mean that once a changeling assumes a new form, that they must stay in that form for ten minutes so that they may then use the spell again to dismiss it, returning to their true form, and then waiting another ten minutes to assume a new form? And if not, wouldn't it be better for the Special line to read something like: "Special You stay in the new form until you dismiss shift shape to revert to your true form or until you die."?

**Comment by Foradain** [comment]
So what happens if the changeling dismisses the spell? 'Cause the text still says it can be dismissed...

**Comment by TNychka** [comment]
Correct, missed that line. Fixed in scribe, foundryVTT patch pending
