### ISSUE TITLE
Hoping to Help

### ISSUE THREAD

**Issue by CaptainClemm** [TNychka/Pathfinder2eConversion#83]
Hi, 

I'm a big fan of Eberron and am planning to switch my 5e game to p2e in the next few sessions. I'd be very interested in helping to expand this resource as I already think it's invaluable. 
I already own several of the Eberron books in either digital or physical form including Rising From The Last War, Exploring Eberron, Chronicles of Eberron, Eberron Campaign Setting, Sharn: City of Towers and more. 

Please feel free to contact me on discord or by email to talk about how I could contribute or help out.
Discord: KeyboardGrease#7808
Email: jacob.l.clements@gmail.com

**Comment by XcorB** [comment]
I've been doing the same 5e to pf2e conversion in last couple of months, so happy to help where I can

**Comment by TNychka** [comment]
Hey @CaptainClemm and @XcorB, my apologies for the super late reply. Please feel free to reach out to me at 360broscope on discord to chat more about opportunities, or in the https://discord.gg/QfnR8Hzt eberron discord pathfinder channel
