### ISSUE TITLE
Foundry: various typo fixes

### ISSUE THREAD

**Issue by JacksonBockus** [TNychka/Pathfinder2eConversion#84]
- "eberron shards" should be "Eberron shards" in several cases, and "Eberon shards" should be "Eberron shards". 
- "Psi-Blade" should have its description updated to better indicate what it is, and source should be changed from the CRB to Pathfinder's Guide to Eberron
- Item names should be use title case in general for consistency with the built-in Equipment compendium. So for instance "Clothing, darkweave" should be "Clothing, Darkweave" and "Arcane signet ring" should be "Arcane Signet Ring". The exception is treasure items, which in general seem to use sentence case.
- Artifice Tools should be Artificer's Tools
- Spellshard(Blank) should have a space between Spellshard and the parenthesis: "Spellshard (Blank)"
- Resist Magic (warforged) should be Resist Magic (Warforged) for consistency
- Many description fields have some loose `div`s floating around that cause the font to be inconsistent.

**Comment by TNychka** [comment]
Resolved by commit https://github.com/TNychka/Pathfinder2eConversion/commit/5912ca10d4c4e7915f01d041a23e2928b811df4a, live in version 1.6.6 of the scribe document and v 2.2.1 of the foundry module
