### ISSUE TITLE
Null pointer exception when importing using Pathmuncher

### ISSUE THREAD

**Issue by draconas1** [TNychka/Pathfinder2eConversion#86]
If using Pathmuncher to import characters, attempting to select an Eberron domain results in a null pointer exception, killing the import.  

When doing an import from pathbuilder where deity is freetext, I get a dropdown to select a deity, if I select an Eberron deity the import crashes wit an exception in the console, selecting a standard entity succeeds in the import.  

(recreate steps, use pathbuilder web to create a cloistered cleric of the silver flame at level 1, attempt to import into foundry using the json id).  I have tried Silver Flame, Sovereign host and a few of the Hosts individual deities with the same result.  

* Foundry Version: V11 build 311
* Pathfinder system version: 5.7.2 
* Pathmuncher version: 0.91
* Pathfinders Guide Version 2.2.2

Error message
```
foundry.js:6570 TypeError: Cannot read properties of undefined (reading 'system')
    at #evaluateChoices (Pathmuncher.js:814:46)
    at async #addGrantedRules (Pathmuncher.js:1021:1)
    at async #addGrantedItems (Pathmuncher.js:1202:1)
    at async #addGrantedItems (Pathmuncher.js:1180:1)
    at async #processGenericCompendiumLookup (Pathmuncher.js:530:1)
    at async Pathmuncher.processCharacter (Pathmuncher.js:2345:1)
    at async PathmuncherImporter._updateObject (PathmuncherImporter.js:104:1)
    at async PathmuncherImporter._onSubmit (foundry.js:6567:7)
_onSubmit @ foundry.js:6570
````

Have attached the json data that was logged. 
[errorlog.json](https://github.com/TNychka/Pathfinder2eConversion/files/13061614/errorlog.json)

**Comment by TNychka** [comment]
I investigated this issue, and it appears that the latest version of Pathmuncher resolves this bug. The Deity must exactly match the Eberron Compenium name (ie. 'The Silver Flame') and there must be a module mapping in the Pathmuncher settings .
![image](https://github.com/TNychka/Pathfinder2eConversion/assets/8963665/0fb98079-f5e0-470c-8e45-37c10c05e05d)

I was not aware of Pathmuncher before this, so I'll do a pass on the pathbuilder module, confirm Pathmuncher functionality, and write a small piece of documentation on the setup.

Closing as no repro, if the update does not resolve this issue please feel free to reopen it

**Comment by draconas1** [comment]
Thanks, that's great news :)

Also thanks for all the work on the module, I love it.
