### ISSUE TITLE
Some Ancestries/Heritages/Backgrounds/Deities Cannot be Added to Character Sheet

### ISSUE THREAD

**Issue by Jlucchesi7786** [TNychka/Pathfinder2eConversion#87]
The Bugbear, Shifter, and Warforged Ancestries can all not be added to a freshly opened player character sheet. When attempting to click and drag from the Eberron Ancestries compendium, the three failed ancestries give an error message that says `Cannot read properties of undefined (reading '0')`. The other two ancestries can be added without issue. I have found some of the heritages and backgrounds to have the same error as well. 
I checked Eberron Ancestries, Eberron Heritages, Eberron Backgrounds, and Eberron Deities compendiums and have listed below the name of all of the items that produced the same error.

Affected Ancestries: Bugbear, Shifter, Warforged
Affected Heritages: 
- Thradaask Guul'dar
- Du'ulora Kalashtar (all three), Hashalaq Kalashtar (all three), Kalaraq Kalashtar Commander, Tsucora Kalashtar Intimidator
- Beasthide Shifter, Cliffwalk Shifter, Dreamsight Shifter, Gorebrute Shifter, Longstride Shifter, Longtooth Shifter, Razorclaw Shifter, Swiftwing Shifter, Truedive Shifter, Wildhunt Shifter
- Juggernaut Warforged, Prototype Warforged, Skirmisher Warforged, Vanguard Warforged
- Barrakas Clan, Therendor Clan
- Mark of Detection, Mark of Finding, Mark of Handling, Mark of Healing, Mark of Making, Mark of Passage, Mark of Scribing, Mark of Sentinel, Mark of Shadow, Mark of Storm, Mark of Warding

Affected Backgrounds: All (Excoriate, Foundling, House Agent, House Orphan, House Scion)
Affected Deities: The Sovereign Host

My foundry is Release version 11.315, and my version of this module is 2.3.0. I'd love to use this to run a future pathfinder game set in Eberron, but I can't while this error is present. If I'm missing something that I need to do, please let me know.

**Comment by mcdaddytalk** [comment]
Can you update to version 2.3.2 and see if it persists?   I'm on V11.315, PF2e 5.82, PF2Eberron 2.3.2 and cannot recreate your issue

**Comment by Jlucchesi7786** [comment]
I will do that and respond in a moment!

**Comment by Jlucchesi7786** [comment]
It turns out I was already on PF2Eberron 2.3.2! I downloaded it earlier today. 
I also checked and I am on PF2e 5.8.2 as well. 

I closed and reopened my test game world that I made and the issue persists on my end.

**Comment by mcdaddytalk** [comment]
I'll try on a fresh install and see if I can replicate.

**Comment by mcdaddytalk** [comment]
Fresh install and no issues. can you post full error from console?  maybe capture steps in a video?

**Comment by Jlucchesi7786** [comment]
Here's a screenshot of the full error message: ![image](https://github.com/TNychka/Pathfinder2eConversion/assets/28420975/99c5f40c-8959-4b4b-b453-3f7d35126d8e)

I don't currently have video recording software on my computer, but I can grab some if it would be helpful.

**Comment by mcdaddytalk** [comment]
Errors look like they are coming from Tokenizer.  Can you deactivate this module and see if the error persists (and you can add from compendium).  Also what version of Tokenizer are you using?

**Comment by Jlucchesi7786** [comment]
My Tokenizer is v4.2.6, although it is not currently enabled. I will try to uninstall it real quick and report back.

**Comment by Jlucchesi7786** [comment]
I have uninstalled it, the issue persists. The full path to the "Tokenizer" is `E:\Program Files\FoundryVTT\Foundry Virtual Tabletop\resources\app\node_modules\htmlparser2\lib\Tokenizer.js` which does not appear to be a module. My modules directory is `C:\Users\Jackson\AppData\Local\FoundryVTT\Data\modules`, which does not contain the Tokenizer module any more.

**Comment by mcdaddytalk** [comment]
When you updated to v11 310 or later did you do an update in place?   There were some updates that required a fresh install to get the latest packages for Foundry app (especially for windows installs)

**Comment by Jlucchesi7786** [comment]
When I updated to v11.315 (previously was on v9.280) I was forced to get a fresh install. The User Data path (`C:/Users/Jackson/AppData/Local/FoundryVTT`) does not seemed to have changed from when it was on version 9, but the path to the "Tokenizer" in my previous comment is outside that path so I am not sure if that is the issue

**Comment by Jlucchesi7786** [comment]
I've found a reddit [post](https://www.reddit.com/r/FoundryVTT/comments/16a4zoh/please_help_problems_with_undefined_0_errors_in/) that details a similar error message and it suggests to do a clean install, which I guess I did not do before? I thought downloading a v11 setup.exe would be enough to do it for me but apparently not. I'll post an update when I can.

**Comment by Jlucchesi7786** [comment]
Ok, it now works.
I set up a new User Data folder, and deleted both of my Foundry appdata folders (two disks) and did a new install using the Foundry setup.exe. 
I still have no idea what the problem was, but I haven't had any issues in my preliminary testing of a new game world.
